--- 
title: "EC282 INTRODUCITON TO ECONOMETRICS"
author: "Onur Altındağ"
date: "Last update: `r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This book teaches econometrics like a 21st century humanoid would want to learn it."
---

#I REALLY HATE TRYING TO FIGURE THIS OUT 
# Course Logistics and using R   


## Goals 

* Course introduction, syllabus, general logistics, etc. 
* Install R and RStudio. Some pep talk on "how to cope with coding frustration". 
* Best practices relating to code/script development in the RStudio Integrated Development Environment (IDE).
* Areas of caution and some never-do's. 

## Course information 

This is an **introductory** econometrics course that aims to provide you the basic set of tools to conduct **data analysis and interpretation** based on economic theory. The focus of the course is the theoretical and empirical foundations of statistical inference and modeling. We will study the basic mechanics of multivariate regression, problems related to its implementation and how to solve them. Towards the end of the semester, subject to a time constraint, we will also discuss issues related to in-sample and out-of-sample prediction problems. The course aims to be application oriented and you should develop, to the extend possible, some programming skills in **R**. At the end of the semester, I expect you to be familar with RStudio interface, basic data manipulation, obtaining and interpreting the sample statistics, conduct meaningful regression analysis and prediction. Importantly, we will not talk much about the elephant in the room: causal interpretation of any empirical analysis, which is left for the next metrics class that you will take.  

## Requirements 

**Textbook**: 

I will mainly use this web page and upload my hand to provide you some material and upload my hand-written lecture notes as well. There are two main textbooks that I heavily rely on to explain the theoretical framework: <br> 
[*Studenmund’s Using Econometrics:  A Practical Guide*](https://www.amazon.com/Using-Econometrics-Practical-Guide-7th/dp/013418274X). <br>
[*Introductory Econometrics: A Modern Approach*](https://www.amazon.com/Introductory-Econometrics-Modern-Approach-MindTap/dp/1337558869/ref=sr_1_3?crid=2NY3RCI1XN2JY&keywords=wooldridge+introductory+econometrics&qid=1578184923&s=books&sprefix=wooldri%2Cstripbooks%2C141&sr=1-3). <br>

Feel free to purchase an older edition or rent them. The 


